version: '3.8'
services:
  users-pokedex:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pokedex-react
      POSTGRES_PASSWORD: poke321
      POSTGRES_DB: users
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: